
export const REGISTER_USER_SUCCESFULL = "REGISTER_USER_SUCCESFULL"
export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST"
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR"
 

export const LOGIN_USER_SUCCESFULL = "LOGIN_USER_SUCCESFULL"
export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST"
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR"
